print("^" * 20)
print("   연산 프로그램")
print("^" * 20)
#a = int(input("첫 번째 값: "))
#b = int(input("두 번째 값: "))
print("계산할 두 수를 공백으로 구분해 차례대로 넣어주세요")
a, b = map(int, input().split())
print("^" * 20)

print(f'{a} + {b} = {a + b}')
print(f'{a} - {b} = {a - b}')
print(f'{a} * {b} = {a * b}')
print(f'{a} / {b} = {a / b}')
print(f'{a} ** {b} = {a ** b}')
print(f'{a} // {b} = {a // b}')
print(f'{a} % {b} = {a % b}')